language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - composer self-update
    - composer --prefer-source install

script:
    - mkdir -p build/logs
    - phpunit -c test/phpunit.xml.dist

after_script:
    - php vendor/bin/coveralls -v
